stages:
  - format
  - test
  - network_test

fmt:
  image: rustdocker/rust:nightly
  stage: format
  tags:
    - privileged
  script:
    - cargo fmt --check

tests:
  image: rustdocker/rust:nightly
  stage: test
  tags:
    - privileged
  script:
    - apt-get update
    - apt-get install libssl-dev -y
    - mv -f ./certificates/DO_NOT_USE.key ./certificates/server.key
    - mv -f ./certificates/DO_NOT_USE.crt ./certificates/server.crt
    - cargo test

network_test:
  image: rustdocker/rust:nightly
  stage: network_test
  tags:
    - privileged
  script:
    - apt-get update
    - apt-get install iproute2 libssl-dev -y
    - mv -f ./certificates/DO_NOT_USE.key ./certificates/server.key
    - mv -f ./certificates/DO_NOT_USE.crt ./certificates/server.crt
    - chmod +x ./tests/realistic_network/configure_interface.sh
    - ./tests/realistic_network/configure_interface.sh
    - cargo test --release